services:
  - type: web
    name: vicky-bot-fase1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: META_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        value: "712597741555047"
      - key: VERIFY_TOKEN
        value: vicky-verify-2025
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GSHEET_PROSPECTS_ID
        sync: false
      - key: GSHEET_SOLICITUDES_ID
        sync: false
      - key: GSHEET_PROSPECTS_TITLE
        value: Prospectos SECOM Auto
      - key: GSHEET_SOLICITUDES_TITLE
        value: Solicitudes Vicky
      - key: ADVISOR_NOTIFY_NUMBER
        value: "5216682478005"
